WebProje/Areas/Admin/Models/SettingManagement/NewSettingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.SettingManagement
{
    public class NewSettingViewModel
    {
        public Settings Setting { get; set; }
    }
}

WebProje/Areas/Admin/Models/SettingManagement/ShowSettingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.SettingManagement
{
    public class ShowSettingViewModel
    {
        public List<Settings> SettingList { get; set; }
    }
}

WebProje/Areas/Admin/Controllers/SettingManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hotel.BI.Interface;
using Hotel.Model.DataModel;
using WebProje.Areas.Admin.Models.SettingManagement;

namespace WebProje.Areas.Admin.Controllers
{
    [Authorize]
    public class SettingManagementController : Controller
    {
        private ISettingsManagement _settingsManagement;

        public SettingManagementController(ISettingsManagement settingsManagement)
        {
            _settingsManagement = settingsManagement;
        }

        // GET: Admin/SettingManagement
        public ActionResult Index()
        {
            ShowSettingViewModel model = new ShowSettingViewModel()
            {
                SettingList = _settingsManagement.GetAll().OrderBy(s=>s.Name).ToList()
            };
            return View(model);
        }

        public ActionResult NewSetting(int? id)
        {
            NewSettingViewModel model = new NewSettingViewModel();
            if (id == null)
            {
                model.Setting = new Settings();
            }
            else
            {
                model.Setting = _settingsManagement.Get(s => s.ID == id);
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult NewSetting(NewSettingViewModel model)
        {
            try
            {
                _settingsManagement.AddOrUpdate(model.Setting);
                this.SuccessMessage($"Setting <b>({model.Setting.Name})</b> has been saved!");
            }
            catch (Exception e)
            {
                this.ErrorMessage($"Setting <b>({model.Setting.Name})</b> could not saved! ({e.Message})");
            }

            return RedirectToAction("Index");
        }
    }
}

WebProje/Areas/Admin/Views/SettingManagement/Index.cshtml
@model WebProje.Areas.Admin.Models.SettingManagement.ShowSettingViewModel
@{
    ViewBag.Title = "Setting Management";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="user-data m-b-30">
    <div class="table-data__tool">
        <div class="table-data__tool-left">
            <h3 class="title-3">
                <i class="zmdi zmdi-settings"></i>Settings
            </h3>
        </div>
        <div class="table-data__tool-right">
            <h3 class="title-3">
                <a href="@Url.Action("NewSetting", "SettingManagement")" class="au-btn au-btn-icon au-btn--green au-btn--small">
                    <i class="zmdi zmdi-plus"></i>Add New Setting
                </a>
            </h3>
        </div>
    </div>
    <div class="table-responsive table-data">
        <table class="table">
            <thead>
                <tr>
                    <td>name</td>
                    <td>keyword</td>
                    <td>value</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var setting in Model.SettingList)
                {
                    <tr>
                        <td>
                            <span class="role admin">@setting.Name</span>
                        </td>
                        <td>
                            <span class="role user">@setting.Keyword</span>
                        </td>
                        <td>
                            <span class="role member">@setting.Value</span>
                        </td>
                        <td>
                            <span class="more">
                                <a href="@Url.Action("NewSetting","SettingManagement", new { id=setting.ID})"><i class="zmdi zmdi-more"></i></a>
                            </span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Style
{
    <style>
        .table-data {
            height: 600px !important;
        }
        .role {
            text-transform: none;
        }
    </style>
}

WebProje/Areas/Admin/Views/SettingManagement/NewSetting.cshtml
@model WebProje.Areas.Admin.Models.SettingManagement.NewSettingViewModel
@{
    ViewBag.Title = "New Setting";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        New <strong>Setting</strong>
    </div>
    @using (Html.BeginForm("NewSetting", "SettingManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(model => model.Setting.ID)
            <div class="card-body card-block">
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="name" class="form-control-label">Name<span class="required"> *</span></label>
                    </div>
                    <div class="col-12 col-md-9">
                        @if (Model.Setting.ID == 0)
                        {
                            @Html.EditorFor(model => model.Setting.Name, new { htmlAttributes = new { @class = "form-control", id = "name", name = "name", type = "text", placeholder = "Name", required = "" } })
                        }
                        else
                        {
                            @Html.HiddenFor(model => model.Setting.Name)
                            @Html.EditorFor(model => model.Setting.Name, new { htmlAttributes = new { @class = "form-control", disabled = "" } })
                        }
                        <small class="form-text text-muted">This is setting's name.</small>
                    </div>
                </div> <!--NAME-->
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="keyword" class="form-control-label">Keyword<span class="required"> *</span></label>
                    </div>
                    <div class="col-12 col-md-9">
                        <div class="input-group">
                            </div>,@if (Model.Setting.ID == 0)
                                   {
                                       @Html.EditorFor(model => model.Setting.Keyword, new { htmlAttributes = new { @class = "form-control", id = "keyword", name = "keyword", type = "text", placeholder = "Keyword", required = "" } })
                                   }
                                   else
                                   {
                                       @Html.HiddenFor(model => model.Setting.Keyword)
                                       @Html.EditorFor(model => model.Setting.Keyword, new { htmlAttributes = new { @class = "form-control", disabled = "" } })
                                   }
                        <small class="form-text text-muted">This is setting's keyword.</small>
                    </div>
                </div> <!--KEYWORD-->
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="name" class="form-control-label">Value<span class="required"> *</span></label>
                    </div>
                    <div class="col-12 col-md-9">
                        @Html.EditorFor(model => model.Setting.Value, new { htmlAttributes = new { @class = "form-control", id = "value", name = "value", type = "text", placeholder = "Name", required = "" } })
                        <small class="form-text text-muted">This is setting's value.</small>
                    </div>
                </div> <!--NAME-->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-save"></i> Save
                    </button>
                </div>
            </div>
        }
</div>

@section Style
{
    <style>
        label .required {
            color: red;
        }
    </style>
}