WebProje/Areas/Admin/Models/EmployeeManagement/NewEmployeeViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Hotel.Core.Enum;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.EmployeeManagement
{
    public class NewEmployeeViewModel
    {
        public Employees Employee { get; set; }
        public List<EnumHelpers> GenderList { get; set; }
    }
}

WebProje/Areas/Admin/Models/EmployeeManagement/ShowEmployeeViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Hotel.Core.Enum;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.EmployeeManagement
{
    public class ShowEmployeeViewModel
    {
        public List<Employees> EmployeeList { get; set; }
    }
}

WebProje/Areas/Admin/Controllers/EmployeeManagementController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hotel.BI.Interface;
using Hotel.Core.Enum;
using Hotel.Model.DataModel;
using WebProje.Areas.Admin.Models.EmployeeManagement;

namespace WebProje.Areas.Admin.Controllers
{
    [Authorize]
    public class EmployeeManagementController : Controller
    {
        private IEmployeesManagement _employeesManagement;

        public EmployeeManagementController(IEmployeesManagement employeesManagement)
        {
            _employeesManagement = employeesManagement;
        }

        // GET: Admin/Employee
        public ActionResult Index()
        {
            ShowEmployeeViewModel model = new ShowEmployeeViewModel()
            {
                EmployeeList = _employeesManagement.GetAll().OrderBy(d=>d.Name).ToList()
            };

            return View(model);
        }

        public ActionResult NewEmployee(int? id)
        {
            NewEmployeeViewModel model = new NewEmployeeViewModel();

            model.GenderList = EnumHelpers.ConvertEnumToList(typeof(Genders));

            List<string> CountryList = new List<string>();
            CultureInfo[] CInfoList = CultureInfo.GetCultures(CultureTypes.SpecificCultures);
            foreach (CultureInfo CInfo in CInfoList)
            {
                RegionInfo R = new RegionInfo(CInfo.LCID);
                if (!(CountryList.Contains(R.EnglishName)))
                {
                    CountryList.Add(R.EnglishName);
                }
            }

            CountryList.Sort();
            ViewBag.CountryList = CountryList;

            if (id == null)
            {
                model.Employee = new Employees();
            }
            else
            {
                model.Employee = _employeesManagement.Get(d => d.ID == id);
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult NewEmployee(NewEmployeeViewModel model)
        {
            try
            {
                _employeesManagement.AddOrUpdate(model.Employee);

                this.SuccessMessage("Employee has been saved!");
            }
            catch
            {
                this.ErrorMessage("Employee could not be saved!");
            }

            return RedirectToAction("Index");
        }

        public ActionResult DeleteEmployee(int id)
        {
            _employeesManagement.Delete(id);

            this.WarningMessage("Employee has been deleted!");

            return RedirectToAction("Index");
        }
    }
}

WebProje/Areas/Admin/Views/EmployeeManagement/Index.cshtml
@using Hotel.Core.Enum
@model WebProje.Areas.Admin.Models.EmployeeManagement.ShowEmployeeViewModel
@{
    ViewBag.Title = "Employee Management";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <!-- EMPLOYEES DATA TABLE -->
    <div class="table-data__tool">
        <div class="table-data__tool-left">
            <h3 class="title-5 m-b-35">Employees</h3>
        </div>
        <div class="table-data__tool-right">
            <a href="@Url.Action("NewEmployee","EmployeeManagement")" class="au-btn au-btn-icon au-btn--green au-btn--small">
                <i class="zmdi zmdi-plus"></i>Add New Employee
            </a>
        </div>
    </div>
    <div class="table-responsive table-responsive-data2">
        <table class="table table-data2">
            <thead>
                <tr>
                    <th>id</th>
                    <th>national id</th>
                    <th>name</th>
                    <th>birth date</th>
                    <th>gender</th>
                    <th>email</th>
                    <th>phone</th>
                    <th>title</th>
                    <th>tooltips</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var employee in Model.EmployeeList)
                {
                <tr class="tr-shadow">
                    <td>@employee.ID</td>
                    <td>@employee.NationalID</td>
                    <td>@employee.Name.ToUpper() @employee.Surname.ToUpper()</td>
                    <td>@employee.BirthDate.ToShortDateString()</td>
                    @if (employee.Gender == "F")
                    {
                        <td class="desc">@Enum.GetName(typeof(Genders), 2)</td>
                    }
                    else
                    {
                        <td class="desc">@Enum.GetName(typeof(Genders), 1)</td>
                    }
                    <td>
                        <a href="mailto:@employee.Email"><span class="block-email">@employee.Email</span></a>
                    </td>
                    <td>
                        <span class="status--process">@employee.Phone</span>
                    </td>
                    <td>
                        <span class="status--denied">@employee.Title</span>
                    </td>
                    <td>
                        <div class="table-data-feature">
                            <a href="@Url.Action("NewEmployee","EmployeeManagement",new{id=employee.ID})" class="item item-edit" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
                                <i class="zmdi zmdi-edit"></i>
                            </a>
                            <a href="@Url.Action("DeleteEmployee","EmployeeManagement",new{id=employee.ID})" class="item item-delete" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete">
                                <i class="zmdi zmdi-delete"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                    <tr class="spacer"></tr>
                }
            </tbody>
        </table>
    </div>
    <!-- END DATA TABLE -->
</div>

@section Style
{
    <style>
        .table-data-feature a.item:hover i {
            color: white;
        }

        .table-data-feature a.item-edit:hover {
            background: #fad562;
        }

        .table-data-feature a.item-delete:hover {
            background: #f55d5d;
        }
    </style>
}

WebProje/Areas/Admin/Views/EmployeeManagement/NewEmployee.cshtml
@model WebProje.Areas.Admin.Models.EmployeeManagement.NewEmployeeViewModel
@{
    ViewBag.Title = "New Employee";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        New <strong>Employee</strong>
    </div>
    @using (Html.BeginForm("NewEmployee", "EmployeeManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(model => model.Employee.ID)
        <div class="card-body card-block">
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="nationalid" class="form-control-label">National ID<span class="required"> *</span></label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Employee.NationalID, new { htmlAttributes = new { @class = "form-control", id = "nationalid", name = "nationalid", type = "number", placeholder = "National ID", required = "" } })
                    <small class="form-text text-muted">This is employee's national identity number</small>
                </div>
            </div> <!--NATIONAL ID-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="name" class="form-control-label">Name<span class="required"> *</span></label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Employee.Name, new { htmlAttributes = new { @class = "form-control", id = "name", name = "name", type = "text", placeholder = "Name", required = "" } })
                    <small class="form-text text-muted">This is employee's name</small>
                </div>
            </div> <!--NAME-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="surname" class="form-control-label">Surname<span class="required"> *</span></label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Employee.Surname, new { htmlAttributes = new { @class = "form-control", id = "surname", name = "surname", type = "text", placeholder = "Surname", required = "" } })
                    <small class="form-text text-muted">This is employee's surname</small>
                </div>
            </div> <!--SURNAME-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="birthdate" class="form-control-label">Birth Date<span class="required"> *</span></label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Employee.BirthDate, new { htmlAttributes = new { @class = "form-control datepicker", id = "birthdate", name = "birthdate", type = "date", required = "", @Value = Model.Employee.BirthDate.ToString("yyyy-MM-dd") } })
                    <small class="form-text text-muted">This is employee's birth date.</small>
                </div>
            </div> <!--BIRTHDAY-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="gender" class="form-control-label">Gender<span class="required"> *</span></label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.DropDownListFor(x => x.Employee.Gender, new SelectList(Model.GenderList, "Description", "Name"), "Please Select", new { @class = "form-control", name = "gender", id = "gender", required = "" })
                    <small class="form-text text-muted">This is employee's gender</small>
                </div>
            </div> <!--GENDER-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="phone" class="form-control-label">Phone Number<span class="required"> *</span></label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Employee.Phone, new { htmlAttributes = new { @class = "form-control", id = "phone", name = "phone", placeholder = "Phone", type = "tel", required="" } })
                    <small class="form-text text-muted">This is employee's phone number</small>
                </div>
            </div> <!--PHONE-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="email" class="form-control-label">E-Mail</label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Employee.Email, new { htmlAttributes = new { @class = "form-control", id = "email", name = "email", type = "email", placeholder = "E-Mail" } })
                    <small class="help-block form-text">This is employee's e-mail</small>
                </div>
            </div> <!--E-MAIL-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="title" class="form-control-label">Title</label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Employee.Title, new { htmlAttributes = new { @class = "form-control", id = "title", name = "title", placeholder = "Title", type = "text" } })
                    <small class="form-text text-muted">This is employee's title</small>
                </div>
            </div> <!--TITLE-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="address" class="form-control-label">Address</label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.TextAreaFor(model => model.Employee.Address, new { @class = "form-control", id = "address", name = "address", rows = "3", placeholder = "Address" })
                </div>
            </div> <!--ADDRESS-->
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary btn-sm">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    }
</div>

@section Style
{
    <style>
        label .required {
            color: red;
        }
    </style>
}