WebProje/Areas/Admin/Models/RoomManagement/NewRoomViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Hotel.Core.Enum;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.RoomManagement
{
    public class NewRoomViewModel
    {
        public Rooms Room { get; set; }
        public List<RoomTypes> RoomTypeList { get; set; }
    }
}

WebProje/Areas/Admin/Models/RoomManagement/ShowRoomViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Hotel.Core.Enum;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.RoomManagement
{
    public class ShowRoomViewModel
    {
        public List<Rooms> RoomList { get; set; }
    }
}

WebProje/Areas/Admin/Controllers/RoomManagementController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hotel.BI.Interface;
using Hotel.Model.DataModel;
using WebProje.Areas.Admin.Models.RoomManagement;

namespace WebProje.Areas.Admin.Controllers
{
    [Authorize]
    public class RoomManagementController : Controller
    {
        private IRoomsManagement _roomsManagement;
        private IRoomTypesManagement _roomTypesManagement;
        private IBooksManagement _booksManagement;

        public RoomManagementController(IRoomsManagement roomsManagement, IRoomTypesManagement roomTypesManagement, IBooksManagement booksManagement)
        {
            _roomsManagement = roomsManagement;
            _roomTypesManagement = roomTypesManagement;
            _booksManagement = booksManagement;
        }

        // GET: Admin/RoomManagement
        public ActionResult Index()
        {
            ShowRoomViewModel model = new ShowRoomViewModel()
            {
                RoomList = _roomsManagement.GetAll().OrderBy(r => r.ID).ToList(),
                BookList = _booksManagement.GetAll().OrderByDescending(b=>b.ArrivalDate).ToList()
            };
            foreach (var room in model.RoomList)
            {
                List<Books> books = _booksManagement.GetAll(b => b.RoomID == room.ID && !b.IsCancelled).OrderByDescending(b => b.ArrivalDate).Take(1).ToList();
                if (books.Count > 0)
                {
                    if (DateHelper.IncludeDate(books[books.Count - 1].ArrivalDate, books[books.Count - 1].DepartureDate))
                    {
                        room.Books.Add(books[books.Count - 1]);
                    }
                }
            }
            return View(model);
        }

        public ActionResult NewRoom(int? id)
        {
            NewRoomViewModel model = new NewRoomViewModel()
            {
                RoomTypeList = _roomTypesManagement.GetAll().OrderBy(r => r.Capacity).ToList()
            };

            if (id == null)
            {
                model.Room = new Rooms();
            }
            else
            {
                model.Room = _roomsManagement.Get(r => r.ID == id);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult NewRoom(NewRoomViewModel model)
        {
            try
            {
                _roomsManagement.AddOrUpdate(model.Room);

                this.SuccessMessage($"Room <b>({model.Room.RoomNo})</b> has been saved!");
            }
            catch (DbUpdateException e)
            {
                this.ErrorMessage($"Room <b>({model.Room.RoomNo})</b> already exist! ({e.Message})");
            }
            catch (Exception e)
            {
                this.ErrorMessage($"Room <b>({model.Room.RoomNo})</b> could not add! ({e.Message})");
            }

            return RedirectToAction("Index");
        }

        public ActionResult DeleteRoom(int id)
        {
            try
            {
                var room = _roomsManagement.Get(r => r.ID == id);
                _roomsManagement.Delete(id);

                this.WarningMessage($"<b>{room.RoomNo}</b> has been deleted!");
            }
            catch
            {
                this.ErrorMessage($"Room No <b>{id}</b> not found!");
            }
            return RedirectToAction("Index");
        }
    }
}

WebProje/Areas/Admin/Views/RoomManagement/Index.cshtml
@model WebProje.Areas.Admin.Models.RoomManagement.ShowRoomViewModel
@{
    ViewBag.Title = "Room Management";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <!-- ROOMS DATA TABLE -->
    <div class="top-campaign">
        <div class="table-data__tool">
            <div class="table-data__tool-left">
                <h3 class="title-5 m-b-35">Rooms</h3>
            </div>
            <div class="table-data__tool-right">
                <a href="@Url.Action("NewRoom","RoomManagement")" class="au-btn au-btn-icon au-btn--green au-btn--small">
                    <i class="zmdi zmdi-plus"></i>Add New Room
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-top-campaign">
                <thead>
                <tr>
                    <td>Room No</td>
                    <td>Floor</td>
                    <td>Type</td>
                    <td>Capacity</td>
                    <td>Status</td>
                    <td>Price</td>
                    <td>Tooltip</td>
                </tr>
                </thead>
                <tbody>
                @foreach (var room in Model.RoomList)
                {
                    <tr>
                        <td>@room.RoomNo</td>
                        <td>@room.Floor</td>
                        <td>@room.RoomTypes.Name</td>
                        <td class="text-center">@room.RoomTypes.Capacity</td>
                        @if (room.Books.Count > 0)
                        {
                            if (DateHelper.Between(room.Books.ElementAt(room.Books.Count-1).ArrivalDate, room.Books.ElementAt(room.Books.Count - 1).DepartureDate))
                            {
                                <td class="denied">Reserved</td>

                            }
                            else
                            {
                                <td class="process">Available</td>
                            }
                        }
                        else
                        {
                            <td class="process">Available</td>
                        }
                        <td>$@room.RoomTypes.Price.ToString("N")</td>
                        <td>
                            <a href="@Url.Action("NewRoom", "RoomManagement", new {id = room.ID})" class="au-btn au-btn-icon  au-btn--orange au-btn--small text-center">
                                <i class="zmdi zmdi-edit"></i>
                            </a>
                            <a href="@Url.Action("DeleteRoom", "RoomManagement", new {id = room.ID})" class="au-btn au-btn-icon au-btn--red au-btn--small text-center">
                                <i class="zmdi zmdi-delete"></i>
                            </a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Style
{
    <style>
        table.table td.process {
            color: #00ad5f;
        }

        table.table td.denied {
            color: #fa4251;
        }
        table {
            text-transform: uppercase;
        }
    </style>
}

WebProje/Areas/Admin/Views/RoomManagement/NewRoom.cshtml
@model WebProje.Areas.Admin.Models.RoomManagement.NewRoomViewModel
@{
    ViewBag.Title = "NewRoom";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        New <strong>Room</strong>
    </div>
    @using (Html.BeginForm("NewRoom", "RoomManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(model=>model.Room.ID)
        <div class="card-body card-block">
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="roomtype" class="form-control-label">Room Type<span class="required"> *</span></label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.DropDownListFor(model => model.Room.RoomTypeID, new SelectList(Model.RoomTypeList, "ID", "Name"), new { htmlAttributes = new { @class = "form-control", id = "roomtype", name = "roomtype", required = "" } })
                    <small class="form-text text-muted">This is room's type.</small>
                </div>
            </div> <!--ROOM TYPE-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="roomno" class="form-control-label">Room No<span class="required"> *</span></label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Room.RoomNo, new { htmlAttributes = new { @class = "form-control", id = "roomno", name = "roomno", type = "number", min = "100", step = "1", placeholder ="Room No", required = ""} })
                    <small class="form-text text-muted">This is room's no.</small>
                </div>
            </div> <!--ROOM NO-->
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="roomfloor" class="form-control-label">Floor</label>
                </div>
                <div class="col-12 col-md-9">
                    @Html.EditorFor(model => model.Room.Floor, new { htmlAttributes = new { @class = "form-control", id = "roomfloor", name = "roomfloor", type = "number", min = "0", step = "1", placeholder = "Floor"} })
                    <small class="form-text text-muted">This is room's floor.</small>
                </div>
            </div> <!--FLOOR-->
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary btn-sm">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    }
</div>