WebProje/Areas/Admin/Models/RoomManagement/NewRoomViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Hotel.Core.Enum;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.RoomManagement
{
    public class NewRoomViewModel
    {
        public Rooms Room { get; set; }
        public List<RoomTypes> RoomTypeList { get; set; }
    }
}

WebProje/Areas/Admin/Models/RoomTypeManagement/NewRoomTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.RoomTypeManagement
{
    public class NewRoomTypeViewModel
    {
        public RoomTypes RoomType { get; set; }
    }
}

WebProje/Areas/Admin/Models/RoomTypeManagement/ShowRoomTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Hotel.Model.DataModel;

namespace WebProje.Areas.Admin.Models.RoomTypeManagement
{
    public class ShowRoomTypeViewModel
    {
        public List<RoomTypes> RoomTypeList { get; set; }
    }
}

WebProje/Areas/Admin/Controllers/RoomTypeManagementController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hotel.BI.Interface;
using Hotel.Model.DataModel;
using WebProje.Areas.Admin.Models.RoomTypeManagement;

namespace WebProje.Areas.Admin.Controllers
{
    [Authorize]
    public class RoomTypeManagementController : Controller
    {
        private IRoomTypesManagement _roomTypesManagement;

        public RoomTypeManagementController(IRoomTypesManagement roomTypesManagement)
        {
            _roomTypesManagement = roomTypesManagement;
        }

        // GET: Admin/RoomTypeManagement
        public ActionResult Index()
        {
            ShowRoomTypeViewModel model = new ShowRoomTypeViewModel()
            {
                RoomTypeList = _roomTypesManagement.GetAll().OrderBy(r => r.Capacity).ToList()
            };
            return View(model);
        }



        public ActionResult NewRoomType(int? id)
        {
            NewRoomTypeViewModel model = new NewRoomTypeViewModel();
            model.RoomType = id == null ? new RoomTypes() : _roomTypesManagement.Get(r => r.ID == id);

            return View(model);
        }

        [HttpPost]
        public ActionResult NewRoomType(NewRoomTypeViewModel model, HttpPostedFileBase ImageUrl)
        {
            try
            {
                if (ImageUrl != null)
                {
                    //string dosyaAdi = "room" + model.RoomType.ID + ImageUrl.ContentType;
                    
                    model.RoomType.Image = ImageUrl.FileName;

                    var path = Path.Combine("~/Images/Rooms/" + model.RoomType.Image);
                    ImageUrl.SaveAs(Server.MapPath(path));
                }

                _roomTypesManagement.AddOrUpdate(model.RoomType);

                this.SuccessMessage($"<b>{model.RoomType.Name}</b> has been saved!");
            }
            catch (Exception e)
            {
                this.ErrorMessage($"<b>{model.RoomType.Name}</b> could not be saved! ({e.Message})");
            }

            return RedirectToAction("Index");
        }

        public ActionResult DeleteRoomType(int id)
        {
            try
            {
                var roomType = _roomTypesManagement.Get(r => r.ID == id);

                _roomTypesManagement.Delete(id);

                this.WarningMessage($"<b>{roomType.Name}</b> has been deleted!");
            }
            catch
            {
                this.ErrorMessage("Room Type not found!");
            }
            return RedirectToAction("Index");
        }
    }
}

WebProje/Areas/Admin/Views/RoomTypeManagement/Index.cshtml
@model WebProje.Areas.Admin.Models.RoomTypeManagement.ShowRoomTypeViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="table-data__tool">
    <div class="table-data__tool-left">
        <h3 class="title-5 m-b-35">Room Types</h3>
    </div>
    <div class="table-data__tool-right">
        <a href="@Url.Action("NewRoomType","RoomTypeManagement")" class="au-btn au-btn-icon au-btn--green au-btn--small">
            <i class="zmdi zmdi-plus"></i>Add New Room Type
        </a>
    </div>
</div>
<div class="row">
    @foreach (var roomType in Model.RoomTypeList)
    {
        <div class="col-md-3">
            <div class="card">
                @if (String.IsNullOrEmpty(roomType.Image))
                {
                    <img class="card-img-top" src="~/Images/Rooms/default.jpg" alt="@roomType.Name">
                }
                else
                {
                    <img class="card-img-top" src="~/Images/@roomType.Image" alt="@roomType.Name">
                }
                <div class="card-body">
                    <div class="inner-tooltip">
                        <div class="table-data__tool text-center">
                                <a href="@Url.Action("NewRoomType", "RoomTypeManagement", new {id=roomType.ID})" class="au-btn au-btn-icon au-btn--block au-btn--orange au-btn--small">
                                    <i class="zmdi zmdi-edit"></i>
                                </a>
                                <a href="@Url.Action("DeleteRoomType", "RoomTypeManagement", new {id = roomType.ID})" class="au-btn au-btn-icon au-btn--block au-btn--red au-btn--small">
                                    <i class="zmdi zmdi-delete"></i>
                                </a>
                        </div>
                    </div>
                    <h4 class="card-title mb-3">@roomType.Name </h4>
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-top-campaign">
                                <thead>
                                    <tr>
                                        <td>Room Count</td>
                                        <td>Capacity</td>
                                        <td>Price</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>@roomType.Rooms.Count</td>
                                        <td>@roomType.Capacity</td>
                                        <td>$@roomType.Price.ToString("N")</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

WebProje/Areas/Admin/Views/RoomTypeManagement/NewRoomType.cshtml
@model WebProje.Areas.Admin.Models.RoomTypeManagement.NewRoomTypeViewModel
@{
    ViewBag.Title = "New Room Type";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        New <strong>Room Type</strong>
    </div>
    @using (Html.BeginForm("NewRoomType", "RoomTypeManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(model => model.RoomType.ID)
    <div class="card-body card-block">
        <div class="row form-group">
            <div class="col col-md-3">
                <label for="name" class="form-control-label">Name<span class="required"> *</span></label>
            </div>
            <div class="col-12 col-md-9">
                @Html.EditorFor(model => model.RoomType.Name, new { htmlAttributes = new { @class = "form-control", id = "name", name = "name", type = "text", placeholder = "Name", required = "" } })
                <small class="form-text text-muted">This is room type's name.</small>
            </div>
        </div> <!--NAME-->
        <div class="row form-group">
            <div class="col col-md-3">
                <label for="price" class="form-control-label">Price<span class="required"> *</span></label>
            </div>
            <div class="col-12 col-md-9">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-dollar"></i>
                    </div>
                    @Html.EditorFor(model => model.RoomType.Price, new { htmlAttributes = new { @class = "form-control", id = "price", name = "price", type = "number", placeholder = "Price", min = "0", step = "0.01", required = "" } })
                </div>
                <small class="form-text text-muted">This is room's price.</small>
            </div>
        </div> <!--PRICE-->
        <div class="row form-group">
            <div class="col col-md-3">
                <label for="capacity" class="form-control-label">Capacity<span class="required"> *</span></label>
            </div>
            <div class="col-12 col-md-9">
                @Html.EditorFor(model => model.RoomType.Capacity, new { htmlAttributes = new { @class = "form-control", id = "capacity", name = "capacity", type = "number", placeholder = "Capacity", min = "1", step = "1", required = "" } })
                <small class="form-text text-muted">This is room's capacity.</small>
            </div>
        </div> <!--CAPACITY-->
        <div class="row form-group">
            <div class="col col-md-3">
                <label for="image" class=" form-control-label">Image</label>
            </div>
            <div class="col-12 col-md-9">
                <input type="file" id="ImageUrl" name="ImageUrl" class="form-control-file form-control">
            </div>
        </div> <!--IMAGE-->
    </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary btn-sm">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    }
</div>

@section Style
{
    <style>
        label .required {
            color: red;
        }
    </style>
}